/**
 * Generates a Jetpack Compose rig file in the same shape as Dosey's PipRig.kt:
 * an Art object of parsed paths, pivot constants, one choreography function per clip
 * (InfiniteTransition keyframes), and a draw function that replays the part transforms.
 *
 * Baked SVG transforms are emitted as equivalent DrawScope calls; matrix(...) entries
 * become a generated svgMatrix() helper (SVG and Compose share the same affine layout).
 */

import { Easing, RigDoc, RigPart, RigPath, Track } from './model';
import { applyMat, invertMat, matrixOfTransform, parseTransformList } from './transforms';

/** Studio easings → Compose counterparts (null = Compose's default linear). */
const EASING_COMPOSE: Record<Easing, string | null> = {
  linear: null,
  easeIn: 'FastOutLinearInEasing',
  easeOut: 'LinearOutSlowInEasing',
  easeInOut: 'FastOutSlowInEasing',
};

export function exportCompose(doc: RigDoc, packageName: string): string {
  const rigName = pascal(doc.name);
  const lines: string[] = [];
  const w = (s = '') => lines.push(s);

  w(`package ${packageName}`);
  w();
  w(`// GENERATED by Rig Studio from ${doc.name}.svg — regenerate rather than hand-editing geometry.`);
  w('');
  w('import androidx.compose.animation.core.CubicBezierEasing');
  w('import androidx.compose.animation.core.FastOutLinearInEasing');
  w('import androidx.compose.animation.core.FastOutSlowInEasing');
  w('import androidx.compose.animation.core.InfiniteTransition');
  w('import androidx.compose.animation.core.LinearOutSlowInEasing');
  w('import androidx.compose.animation.core.animateFloat');
  w('import androidx.compose.animation.core.infiniteRepeatable');
  w('import androidx.compose.animation.core.keyframes');
  w('import androidx.compose.animation.core.rememberInfiniteTransition');
  w('import androidx.compose.foundation.Canvas');
  w('import androidx.compose.runtime.Composable');
  w('import androidx.compose.runtime.key');
  w('import androidx.compose.ui.Modifier');
  w('import androidx.compose.ui.geometry.Offset');
  w('import androidx.compose.ui.graphics.Color');
  w('import androidx.compose.ui.graphics.Matrix');
  w('import androidx.compose.ui.graphics.Path');
  w('import androidx.compose.ui.graphics.StrokeCap');
  w('import androidx.compose.ui.graphics.StrokeJoin');
  w('import androidx.compose.ui.graphics.drawscope.DrawScope');
  w('import androidx.compose.ui.graphics.drawscope.Fill');
  w('import androidx.compose.ui.graphics.drawscope.Stroke');
  w('import androidx.compose.ui.graphics.drawscope.withTransform');
  w('import androidx.compose.ui.graphics.vector.PathParser');
  w();

  // Moods enum from clips
  w(`enum class ${rigName}Mood {`);
  for (const clip of doc.clips) w(`    ${constName(clip.name)},`);
  w('}');
  w();

  // Entry composable
  w('@Composable');
  w(`fun ${rigName}Rig(mood: ${rigName}Mood, modifier: Modifier = Modifier) {`);
  w('    key(mood) {');
  w(`        val transition = rememberInfiniteTransition(label = "${doc.name}-rig")`);
  w('        val pose = when (mood) {');
  for (const clip of doc.clips) {
    w(`            ${rigName}Mood.${constName(clip.name)} -> ${camel(clip.name)}Pose(transition)`);
  }
  w('        }');
  w('        Canvas(modifier = modifier) {');
  w(`            draw${rigName}(pose)`);
  w('        }');
  w('    }');
  w('}');
  w();

  // Choreography per clip
  for (const clip of doc.clips) {
    w('@Composable');
    w(`private fun ${camel(clip.name)}Pose(transition: InfiniteTransition): Map<String, Float> {`);
    w('    val pose = mutableMapOf<String, Float>()');
    for (const track of clip.tracks) {
      if (track.keyframes.length === 0) continue;
      const channelKey = `${trackName(doc, track)}.${track.channel}`;
      const first = track.keyframes[0].value;
      const last = track.keyframes[track.keyframes.length - 1].value;
      w(`    pose["${channelKey}"] = transition.animateFloat(`);
      w(`        ${f(first)}f, ${f(last)}f,`);
      w('        infiniteRepeatable(keyframes {');
      w(`            durationMillis = ${clip.duration}`);
      track.keyframes.forEach((k, i) => {
        // Compose's `using` sets the easing of the segment LEAVING this keyframe; the
        // studio stores easing on the ARRIVING keyframe — so look one ahead. A custom
        // curve-editor bezier on the arriving key overrides its preset easing.
        const next = track.keyframes[i + 1];
        let suffix = '';
        if (next?.bezier) {
          const [x1, y1, x2, y2] = next.bezier;
          suffix = ` using CubicBezierEasing(${f(x1)}f, ${f(y1)}f, ${f(x2)}f, ${f(y2)}f)`;
        } else if (next && EASING_COMPOSE[next.easing]) {
          suffix = ` using ${EASING_COMPOSE[next.easing]}`;
        }
        w(`            ${f(k.value)}f at ${k.time}${suffix}`);
      });
      w('        }),');
      w(`        label = "${channelKey}"`);
      w('    ).value');
    }
    w('    return pose');
    w('}');
    w();
  }

  // Pivots
  for (const part of doc.parts) {
    w(`private val ${pivotName(part)} = Offset(${f(part.pivot.x)}f, ${f(part.pivot.y)}f)`);
  }
  w(`private val RootPivot = Offset(${f(doc.rootPivot.x)}f, ${f(doc.rootPivot.y)}f)`);
  w();

  // Draw function
  w(`private fun DrawScope.draw${rigName}(pose: Map<String, Float>) {`);
  w(`    val unitScale = minOf(size.width / ${f(doc.viewBox.w)}f, size.height / ${f(doc.viewBox.h)}f)`);
  w('    withTransform({');
  w(`        translate(`);
  w(`            (size.width - ${f(doc.viewBox.w)}f * unitScale) / 2f - ${f(doc.viewBox.x)}f * unitScale,`);
  w(`            (size.height - ${f(doc.viewBox.h)}f * unitScale) / 2f - ${f(doc.viewBox.y)}f * unitScale`);
  w('        )');
  w('        scale(unitScale, unitScale, pivot = Offset.Zero)');
  w('        // root figure channels');
  w('        translate(pose.at("root.tx"), pose.at("root.ty"))');
  w('        scale(pose.at("root.sx", 1f), pose.at("root.sy", 1f), pivot = RootPivot)');
  w('    }) {');
  // Bones/groups have no artwork of their own — they only exist in transform chains.
  for (const part of doc.parts.filter((p) => p.paths.length > 0)) {
    w(`        drawPart_${ident(part.label)}(pose)`);
  }
  w('    }');
  w('}');
  w();

  // Per-part draw functions. Parented parts replay their ancestors' pose transforms
  // first (outermost ancestor → the part itself), so limbs chain exactly as on canvas
  // — including partless bone/group ancestors, whose channels appear only in chains.
  // Keyed channels read from the pose map (ABSOLUTE values); the rest pose is the
  // pose.at() default, so unkeyed channels fall back to it — matching channelValue().
  for (const part of doc.parts.filter((p) => p.paths.length > 0)) {
    w(`private fun DrawScope.drawPart_${ident(part.label)}(pose: Map<String, Float>) {`);
    w('    withTransform({');
    for (const link of [...chainOf(doc, part), part]) {
      w(`        translate(${chan(link, 'tx')}, ${chan(link, 'ty')})`);
      w(`        rotate(${chan(link, 'rotate')}, pivot = ${pivotName(link)})`);
    }
    for (const line of emitTransformCalls(part.transform, '        ')) w(line);
    // Rest scale/skew: innermost, around the pivot in pre-baked local space, so the
    // artwork reshapes along its own axes and the joint stays fixed (matches view.ts).
    const rsx = part.rest?.sx ?? 1;
    const rsy = part.rest?.sy ?? 1;
    const rkx = part.rest?.kx ?? 0;
    const rky = part.rest?.ky ?? 0;
    if (rsx !== 1 || rsy !== 1 || rkx !== 0 || rky !== 0) {
      const pl = applyMat(
        invertMat(matrixOfTransform(part.transform)), part.pivot.x, part.pivot.y,
      );
      if (rkx === 0 && rky === 0) {
        w(
          `        scale(${f(rsx)}f, ${f(rsy)}f, ` +
          `pivot = Offset(${f(pl.x)}f, ${f(pl.y)}f))`,
        );
      } else {
        // Skew has no DrawScope call: fold pivot+scale+skew into one matrix.
        const m = matrixOfTransform(
          `translate(${pl.x},${pl.y}) scale(${rsx},${rsy}) ` +
          `skewX(${rkx}) skewY(${rky}) translate(${-pl.x},${-pl.y})`,
        );
        w(
          `        transform(svgMatrix(${f(m.a)}f, ${f(m.b)}f, ${f(m.c)}f, ` +
          `${f(m.d)}f, ${f(m.e)}f, ${f(m.f)}f))`,
        );
      }
    }
    w('    }) {');
    part.paths.forEach((p, idx) => {
      const inner = emitTransformCalls(p.transform, '            ');
      if (inner.length > 0) {
        w('        withTransform({');
        for (const line of inner) w(line);
        w('        }) {');
        emitPathDraw(w, rigName, part, idx, p, '            ');
        w('        }');
      } else {
        emitPathDraw(w, rigName, part, idx, p, '        ');
      }
    });
    w('    }');
    w('}');
    w();
  }

  // Art object
  w(`private object ${rigName}Art {`);
  for (const part of doc.parts) {
    part.paths.forEach((p, idx) => {
      w(`    val ${pathName(part, idx)} = parse(`);
      w(`        "${sanitizePathData(p.d).replace(/"/g, '\\"')}"`);
      w('    )');
    });
  }
  w('    private fun parse(pathData: String): Path = PathParser().parsePathString(pathData).toPath()');
  w('}');
  w();

  // Helpers
  w('private fun Map<String, Float>.at(key: String, default: Float = 0f): Float = this[key] ?: default');
  w();
  w('/** SVG matrix(a,b,c,d,e,f) as a Compose Matrix: x\' = ax + cy + e, y\' = bx + dy + f. */');
  w('private fun svgMatrix(a: Float, b: Float, c: Float, d: Float, e: Float, f: Float): Matrix {');
  w('    val m = Matrix()');
  w('    m.values[Matrix.ScaleX] = a; m.values[Matrix.SkewY] = b');
  w('    m.values[Matrix.SkewX] = c; m.values[Matrix.ScaleY] = d');
  w('    m.values[Matrix.TranslateX] = e; m.values[Matrix.TranslateY] = f');
  w('    return m');
  w('}');
  w();

  return lines.join('\n');
}

function emitPathDraw(
  w: (s?: string) => void, rigName: string, part: RigPart, idx: number, p: RigPath, indent: string,
): void {
  const ref = `${rigName}Art.${pathName(part, idx)}`;
  if (p.fill) {
    w(`${indent}drawPath(${ref}, ${color(p.fill, p.fillOpacity)}, style = Fill)`);
  }
  if (p.stroke) {
    w(
      `${indent}drawPath(${ref}, ${color(p.stroke, p.strokeOpacity)}, ` +
      `style = Stroke(width = ${f(p.strokeWidth)}f, cap = StrokeCap.Round, join = StrokeJoin.Round))`,
    );
  }
}

/** Baked SVG transform list → DrawTransform calls (outermost first, matching SVG order). */
function emitTransformCalls(transform: string, indent: string): string[] {
  const out: string[] = [];
  for (const t of parseTransformList(transform)) {
    switch (t.type) {
      case 'translate':
        out.push(`${indent}translate(${f(t.tx)}f, ${f(t.ty)}f)`);
        break;
      case 'scale':
        out.push(`${indent}scale(${f(t.sx)}f, ${f(t.sy)}f, pivot = Offset.Zero)`);
        break;
      case 'rotate':
        out.push(`${indent}rotate(${f(t.angle)}f, pivot = Offset(${f(t.cx)}f, ${f(t.cy)}f))`);
        break;
      case 'skewX':
        out.push(
          `${indent}transform(svgMatrix(1f, 0f, ${f(Math.tan((t.angle * Math.PI) / 180))}f, 1f, 0f, 0f))`,
        );
        break;
      case 'skewY':
        out.push(
          `${indent}transform(svgMatrix(1f, ${f(Math.tan((t.angle * Math.PI) / 180))}f, 0f, 1f, 0f, 0f))`,
        );
        break;
      case 'matrix':
        out.push(
          `${indent}transform(svgMatrix(${f(t.a)}f, ${f(t.b)}f, ${f(t.c)}f, ${f(t.d)}f, ${f(t.e)}f, ${f(t.f)}f))`,
        );
        break;
    }
  }
  return out;
}

/** Ancestors of a part (outermost first), cycle-safe. */
function chainOf(doc: RigDoc, part: RigPart): RigPart[] {
  const chain: RigPart[] = [];
  const seen = new Set<string>([part.id]);
  let cur = part.parentId ? doc.parts.find((p) => p.id === part.parentId) : undefined;
  while (cur && !seen.has(cur.id)) {
    chain.unshift(cur);
    seen.add(cur.id);
    const parentId: string | null = cur.parentId;
    cur = parentId ? doc.parts.find((p) => p.id === parentId) : undefined;
  }
  return chain;
}

/** Channel lookup: keyed values are absolute; the rest value is the unkeyed default. */
function chan(part: RigPart, channel: 'rotate' | 'tx' | 'ty'): string {
  const rest = part.rest?.[channel] ?? 0;
  if (rest === 0) return `pose.at("${part.label}.${channel}")`;
  return `pose.at("${part.label}.${channel}", ${f(rest)}f)`;
}

function trackName(doc: RigDoc, track: Track): string {
  if (track.target === 'root') return 'root';
  return doc.parts.find((p) => p.id === track.target)?.label ?? track.target;
}

function color(hex: string, opacity: number): string {
  let h = hex.trim();
  if (h.startsWith('#')) h = h.slice(1);
  if (h.length === 3) h = h.split('').map((c) => c + c).join('');
  const alpha = Math.round(Math.min(1, Math.max(0, opacity)) * 255)
    .toString(16)
    .padStart(2, '0');
  return `Color(0x${(alpha + h).toUpperCase()})`;
}

const f = (n: number) => Number(n.toFixed(4)).toString();

/** Expand scientific notation (2.8e-5) — not every SVG path parser accepts it. */
function sanitizePathData(d: string): string {
  return d.replace(/-?\d*\.?\d+[eE][-+]?\d+/g, (m) =>
    Number(m)
      .toFixed(8)
      .replace(/0+$/, '')
      .replace(/\.$/, ''),
  );
}

function ident(s: string): string {
  return s.replace(/[^A-Za-z0-9_]/g, '_');
}

function pascal(s: string): string {
  return ident(s)
    .split('_')
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join('');
}

function camel(s: string): string {
  const p = pascal(s);
  return p[0].toLowerCase() + p.slice(1);
}

function constName(s: string): string {
  return ident(s).toUpperCase();
}

function pivotName(part: RigPart): string {
  return `Pivot_${ident(part.label)}`;
}

function pathName(part: RigPart, idx: number): string {
  return `${ident(part.label)}_${idx}`;
}
